package inventory;/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : inventory.IInventoryVisitor.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/



/** */
public class IInventoryVisitor {
	/** */
	public void visit(Dancer i) {
	}
	
	/** */
	public void visit(RDancer i) {
	}
	
	/** */
	public void visit(Forgetter i) {
	}
	
	/** */
	public void visit(RForgetter i) {
	}
	
	/** */
	public void visit(Paralyzer i) {
	}
	
	/** */
	public void visit(RParalyzer i) {
	}
	
	/** */
	public void visit(Bag i) {
	}
	
	/** */
	public void visit(Glove i) {
	}
	
	/** */
	public void visit(Jacket i) {
	}
	
	/** */
	public void visit(Aminoacid i) {
	}
	
	/** */
	public void visit(Nucleoid i) {
	}
	
	/** */
	public void visit(Protector i) {
	}
}
