package inventory;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : inventory.IInventoryHolder.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/



/** Minden inventory-val rendelkező objektum
 * összefoglaló interfésze */
public interface IInventoryHolder {
	/** Az objektum kötelezően visszaad egy inventory-t */
	public Inventory getInventory();
}
