package inventory;/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : inventory.IInventoryHolder.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


import inventory.Inventory;

/** */
public class IInventoryHolder {
	/** */
	private Inventory inventory;
	
	/** */
	public Inventory getInventory() {
	}
}
