package inventory;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : inventory.InventorySorterVisitor.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


import inventory.IInventoryVisitor;
import item.*;

import java.util.ArrayList;

/** Visitor, amely a kapott inventory szétválogatásáért,
 * illetve a kapott objektumokon végzett műveletekért felel */
public class InventorySorterVisitor implements IInventoryVisitor {
	/** Vitustáncot okozó ágensek */
	private ArrayList<Dancer> dancerItems;
	/** Vitustáncot okozó ágen receptek */
	private ArrayList<RDancer> rdancerItems;
	/** Felejtő ágensek */
	private ArrayList<Forgetter> forgetterItems;
	/** Felejtő ágens receptek */
	private ArrayList<RForgetter> rforgetterItems;
	/** Bénító ágensek */
	private ArrayList<Paralyzer> paralyzerItems;
	/** Bénító ágens receptek */
	private ArrayList<RParalyzer> rpalaryzerItems;
	/** Védő vakcinák */
	private ArrayList<Protector> protectorItems;
	/** Védő vakcina receptek */
	public ArrayList<RProtector> rprotectorItems;
	/** Zsákok */
	private ArrayList<Bag> bagItems;
	/** Kesztyűk */
	private ArrayList<Glove> gloveItems;
	/** Köpenyek */
	private ArrayList<Jacket> jacketItems;
	/** Aminosavak */
	private ArrayList<Aminoacid> aminoacidItems;
	/** Nukleoidok */
	private ArrayList<Nucleoid> nucleoidItems;

	/** A vitustáncot okozó ágens számlálója */
	public void visit(Dancer i) {
	}

	/** A vitustáncot okozó ágens receptjének számlálója */
	public void visit(RDancer i) {
	}

	/** A felejtő ágens számlálója */
	public void visit(Forgetter i) {
	}

	/** A felejtő ágens receptjének számlálója */
	public void visit(RForgetter i) {
	}

	/** A bénító ágens számlálója*/
	public void visit(Paralyzer i) {
	}

	/** A bénító ágens receptjének számlálója */
	public void visit(RParalyzer i) {
	}

	/** A védő vakcina számlálója */
	public void visit(Protector i) {
	}

	/** A védő vakcina receptjének számlálója */
	public void visit(RProtector i) {
	}

	/** A táska számlálója */
	public void visit(Bag i) {
	}

	/** A kesztyű számlálója */
	public void visit(Glove i) {
	}

	/** A köpeny számlálója */
	public void visit(Jacket i) {
	}

	/** Az aminosav számlálója */
	public void visit(Aminoacid i) {
	}

	/** A nukleoid számlálója */
	public void visit(Nucleoid i) {
	}
}
