package inventory;
/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : inventory.InventorySorterVisitor.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


import inventory.IInventoryVisitor;

/** */
public class InventorySorterVisitor implements IInventoryVisitor {
	/** */
	private Dancer[0..*] dancerItems;
	
	/** */
	private RDancer[0..*] rdancerItems;
	
	/** */
	private Forgetter[0..*] forgetterItems;
	
	/** */
	private RForgetter[0..*] rforgetterItems;
	
	/** */
	private Paralyzer[0..*] paralyzerItems;
	
	/** */
	private RParalyzer[0..*] rpalaryzerItems;
	
	/** */
	private Protector[0..*] protectorItems;
	
	/** */
	public RProtector[0..*] rprotectorItems;
	
	/** */
	private Bag[0..*] bagItems;
	
	/** */
	private Glove[0..*] gloveItems;
	
	/** */
	private Jacket[0..*] jacketItems;
	
	/** */
	private Aminoacid[0..*] aminoacidItems;
	
	/** */
	private Nucleoid[0..*] nucleoidItems;
}
