package inventory;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : inventory.IStorable.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


/**
 * Minden tárolható objektum összefoglaló interfésze
 */
public interface IStorable {
    /**
     * Kötelezően fogadandó visitor, az implementáló
     * objektumok saját magukkal hívják a visitor
     * visit függvényét
     */
    public void accept(IInventoryVisitor i);
}
