package inventory;/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : inventory.IStorable.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/



/** */
public class IStorable {
	/** */
	public void accept(IInventoryVisitor i) {
	}
}
