package inventory;/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : inventory.VisitorManager.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


import inventory.IStorable;
import inventory.InventorySorterVisitor;

/** */
public class VisitorManager {
	/** */
	public InventorySorterVisitor sortInventory(Virologist e) {
	}
	
	/** */
	public void hasWonTheGame(Virologist e) {
	}
	
	/** */
	public int checkMaterialCount(Virologist e) {
	}
	
	/** */
	public bool craftRecipe(Virologist v, Recipe r) {
	}
	
	/** */
	public IStorable[0..*] getStealable(Virologist v) {
	}
	
	/** */
	public bool containsGear(Virologist v, Bag g) {
	}
	
	/** */
	public bool containsGear(Virologist v, Glove g) {
	}
	
	/** */
	public bool containsGear(Virologist v, Jacket g) {
	}
}
