package entity;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : entity.Bot.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


import inventory.IStorable;

/** A Bot döntéseit megvalósító osztály */
public class Bot extends Virologist {

	/** A Bot lépését szimuláló függvény */
	public void step() {
	}
	
	/** A Bot egy item felvételéről dönt */
	public void pickUp(IStorable s) {
	}

}
