package entity;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : entity.Player.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


import inventory.IStorable;

/** */
public class Player extends Virologist {
	/** */
	public void step() {
	}
	
	/** */
	public void pickUp(IStorable s) {
	}

}
