package entity;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : entity.Player.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


import inventory.IStorable;

/** Játékos döntéseit reprezentáló osztály */
public class Player extends Virologist {

	/** A játékos döntéseit végrehajtó függvény */
	public void step() {
	}
	
	/** A játékos egy item felvételéről döntő függvény */
	public void pickUp(IStorable s) {
	}

}
