package entity;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : entity.Player.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


import game.Game;
import inventory.IStorable;
import inventory.NotEnoughSpaceException;
import inventory.VisitorManager;
import item.Agent;

/**
 * Játékos döntéseit reprezentáló osztály
 */
public class Player extends Virologist {
    /**
     * Ikon elérési út
     */
    protected String iconPath = "";

    /**
     * Getter - Ikon elérési út
     */
    public String getIconPath() {
        return iconPath;
    }

    /**
     * A játékos döntéseit végrehajtó függvény
     */
    public void step() {
        Game.activeVirologist = this;
        for (Agent a : applied) {
            try {
                a.effect(this);
            } catch (NotEnoughSpaceException ignore) {
            }
        }
    }

    /**
     * A játékos egy item felvételéről döntő függvény
     */
    public void pickUp(IStorable s) {
        if (VisitorManager.hasBear(this) ||VisitorManager.hasDancer(this) ||VisitorManager.hasParalyzer(this))
            return;
        try {
            tile.interactedWith(this);
        } catch (Exception ignored) {
        }
    }

    /**
     * A játékos meghal, mivel egy játékost generálunk
     * a pályára, a játéknak vége
     */
    public void die() {
        Game.exitGame();
    }

}
