package entity;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : entity.Virologist.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


import game.Steppable;
import game.Tile;
import inventory.IInventoryHolder;
import inventory.IStorable;
import inventory.Inventory;
import item.Agent;
import item.Recipe;

/** */
public abstract class Virologist implements Steppable, IInventoryHolder {
	/** */
	private boolean paralyzed;
	
	/** */
	protected Tile tile;
	
	/** */
	private Agent applied;
	
	/** */
	public Inventory getInventory() {
	}
	
	/** */
	public Agent[0..*] getApplied() {
	}
	
	/** */
	public void applyAgent(Agent a) {
	}
	
	/** */
	public void removeApplied(Agent a) {
	}
	
	/** */
	public void setParalyzed(bool b) {
	}
	
	/** */
	public void sortApplied() {
	}
	
	/** */
	public void move(Tile t) {
	}
	
	/** */
	public void robVirologist(Virologist v) {
	}
	
	/** */
	public void makeAgent(Recipe r) {
	}
	
	/** */
	public void useAgent(Virologist v, Agent a) {
	}
	
	/** */
	public abstract void pickUp(IStorable s);
}
