package entity;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : entity.Virologist.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


import game.Steppable;
import game.Tile;
import inventory.IInventoryHolder;
import inventory.IStorable;
import inventory.Inventory;
import item.Agent;
import item.Recipe;

import java.util.ArrayList;

/** Egy közös entitás működését szimuláló osztály */
public abstract class Virologist implements Steppable, IInventoryHolder {
	/** Mező, amelyen a virológus jelenleg áll */
	protected Tile tile;
	/** A virológusunk állapotát tároló változó */
	protected boolean paralyzed;
	/** A virológushoz tartozó inventory */
	protected Inventory inventory;
	/** A virológusra felkent ágensek */
	protected ArrayList<Agent> applied;
	
	/** Getter - Inventory */
	public Inventory getInventory() {
		return inventory;
	}
	
	/** Getter - Felkent ágensek */
	public ArrayList<Agent> getApplied() {
		return applied;
	}
	
	/** Ágens felkenése a virológusra */
	public void applyAgent(Agent a) {
	}
	
	/** Ágens leszedése a virológusról */
	public void removeApplied(Agent a) {
	}
	
	/** A virológus bénult állapotának beállítása */
	public void setParalyzed(boolean p) {
		paralyzed = p;
	}
	
	/** Felkent ágensek lejárati idő szerinti növekvő sorbarendezése */
	public void sortApplied() {
	}
	
	/** A virológus másik mezőre léptetése */
	public void move(Tile t) {
	}
	
	/** Egy másik virológus kirablása */
	public void robVirologist(Virologist v) {
	}
	
	/** Egy ágens recept alapján való létrehozása */
	public void makeAgent(Recipe r) {
	}
	
	/** Ágens felhasználása a virológus által
	 * @param v A célpont
	 * @param a A felhasználni kívánt ágens
	 * */
	public void useAgent(Virologist v, Agent a) {
	}

	/** Leszármazottak által definiálandó működés */
	public abstract void step();
	/** Leszármazott általi döntés egy item felvételéről */
	public abstract void pickUp(IStorable s);
}
