package item;/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.Aminoacid.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


import inventory.IInventoryVisitor;

/** */
public class Aminoacid extends Material {
	/** */
	public void accept(IInventoryVisitor i) {
	}
}
