package item;/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.Bag.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


import inventory.IInventoryHolder;
import inventory.IInventoryVisitor;
import inventory.Inventory;
import item.Agent;

/** */
public class Bag extends Gear implements IInventoryHolder {
	/** */
	public void protect(Virologist v, Agent a) {
	}
	
	/** */
	public void equip(Virologist v) {
	}
	
	/** */
	public void unequip(Virologist v) {
	}
	
	/** */
	public Inventory getInventory() {
	}
	
	/** */
	public void accept(IInventoryVisitor i) {
	}
	
	/** */
	public void protect(Virologist v, Agent a) {
	}
	
	/** */
	public void equip(Virologist v) {
	}
	
	/** */
	public void unequip(Virologist v) {
	}
}
