package item;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.Bag.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import inventory.IInventoryHolder;
import inventory.IInventoryVisitor;
import inventory.Inventory;
import item.Agent;

/** A játékban a zsák tipusú védőfelszerelés. Egy zsákban nem lehet még egy szák.*/
public class Bag extends Gear implements IInventoryHolder {
	/** A paraméterben kapott virológust megvédi a paraméterben kapott ágens ellen. */
	public void protect(Virologist v, Agent a) {
	}

	/** A paraméterben kapott virológus kiválasztja a zsákot. */
	public void equip(Virologist v) {
	}
	
	/** A paraméterben kapott virológus másik védőfelszerelésre vált. */
	public void unequip(Virologist v) {
	}

	/**A visitor tervezési mintát ez a függvény valósítja meg, ez fogja fogadni a zsák típust. */
	public void accept(IInventoryVisitor i) {
	}

	/** Visszaadja a zsák tartalmát.*/
	public Inventory getInventory() {
	}
}
