package item;/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.Dancer.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


import inventory.IInventoryVisitor;
import item.Agent;

/** */
public class Dancer extends Agent {
	/** */
	public void step() {
	}
	
	/** */
	public void effect(Virologist v) {
	}
	
	/** */
	public void decompose(Virologist v) {
	}
	
	/** */
	public void accept(IInventoryVisitor i) {
	}
	
	/** */
	public void protect(Virologist v, Agent a) {
	}
	
	/** */
	public void use(Virologist v1, Virologist v2) {
	}
	
	/** */
	public void effect(Virologist v) {
	}
	
	/** */
	public void decompose(Virologist v) {
	}
	
	/** */
	public void protect(Virologist v, Agent a) {
	}
	
	/** */
	public void use(Virologist v1, Virologist v2) {
	}
}
