package item;/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.Gear.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


import inventory.IStorable;
import item.Agent;

/** */
public abstract class Gear implements IStorable {
	/** */
	protected bool equipped;
	
	/** */
	public abstract void protect(Virologist v, Agent a);
	
	/** */
	public abstract void equip(Virologist v);
	
	/** */
	public abstract void unequip(Virologist v);
}
