package item;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.Gear.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import inventory.IStorable;
import item.Agent;

/** A védőfelszerelések ősosztálya.A virológusok ezek védelem céljából veszik fel*/
public abstract class Gear implements IStorable {
	/** Tárolja, hogy az aktuális védőfelszerelés használatban van. */
	protected boolean equipped;
	
	/**A paraméterben kapott virológust megvédi a paraméterben kapott ágens ellen.*/
	public abstract void protect(Virologist v, Agent a);
	
	/** A paraméterben kapott virológus kiválasztja a védőfelszerelést*/
	public abstract void equip(Virologist v);
	
	/** A paraméterben kapott virológus másik védőfelszerelésre vált.*/
	public abstract void unequip(Virologist v);
}
