package item;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.Glove.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import entity.Virologist;
import inventory.IInventoryVisitor;
import inventory.Inventory;
import inventory.ItemNotFoundException;

/**
 * A játékban a kesztyű tipusú védőfelszerelés.
 */
public class Glove extends Gear {
    /**
     * Hátralévő használatok száma
     */
    public static int DURABILITY = 3;

    /**
     * Konstruktor
     */
    public Glove() {
        super(Glove.DURABILITY);
    }

    /**
     * A paraméterben kapott virológust megvédi a paraméterben kapott ágens ellen.
     *
     * @param v1 A Virológus aki az ágenst keni
     * @param v2 A Virológus akire az ágenst kenik
     * @param a  Az Ágens amit kennek a virológusra
     */
    public void protect(Virologist v1, Virologist v2, Agent a) {
        try {
            v2.removeApplied(a);
            v1.getApplied().add(a);
            v1.getInventory().removeItem(this);
        } catch (ItemNotFoundException ignore) {
            System.out.println("Nincs ilyen felkent ágens a virológuson");
        } catch (Exception e) {
            System.out.println("Nem lehet visszakenni");
        }
    }

    /**
     * A paraméterben kapott virológus kiválasztja a kesztyűt.
     *
     * @param v A Virológus aki felveszi a kesztyűt
     */
    public void equip(Virologist v) {
        equipped = true;
    }

    /**
     * A felszerelést nem lehet használni
     */
    public void use(Virologist v) {
    }

    /**
     * A paraméterben kapott virológus másik védőfelszerelésre vált.
     *
     * @param v A Virológus aki leadja a kesztyűt
     */
    public void unequip(Virologist v) {
        equipped = false;
    }

    /**
     * A visitor tervezési mintát ez a függvény valósítja meg, ez fogja fogadni a kesztyű típust.
     */
    public void accept(IInventoryVisitor i) {
        i.visit(this);
    }

}
