package item;/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.Jacket.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


import inventory.IInventoryVisitor;

/** */
public class Jacket extends Gear {
	/** */
	public void protect(Virologist v, Agent a) {
	}
	
	/** */
	public void equip(Virologist v) {
	}
	
	/** */
	public void unequip(Virologist v) {
	}
	
	/** */
	public void accept(IInventoryVisitor i) {
	}
	
	/** */
	public void protect(Virologist v, Agent a) {
	}
	
	/** */
	public void equip(Virologist v) {
	}
	
	/** */
	public void unequip(Virologist v) {
	}
}
