package item;

import java.io.Serializable;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.Material.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import graphics.IIcon;
import inventory.IInventoryVisitor;
import inventory.IStorable;

/**
 * A játék során felvehető anyagok ősosztálya.
 */
public abstract class Material implements IStorable , Serializable {

    /**
     * A visitor tervezési mintát ez a függvény valósítja meg, ez fogja fogadni az ágens típust.
     */
    public abstract void accept(IInventoryVisitor i);
    /**
     * Getter - Ikon elérési út
     */
    public abstract String getIconPath();
}
