package item;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.Material.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import inventory.IInventoryVisitor;
import inventory.IStorable;

/** A játék során felvehető anyagok ősosztálya.*/
public abstract class Material implements IStorable {

    public abstract void accept(IInventoryVisitor i);
}
