package item;/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.Material.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


import inventory.IStorable;

/** */
public abstract class Material implements IStorable {
}
