package item;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.Protector.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import inventory.IInventoryVisitor;
import item.Agent;

/**Védelmet nyújtó ágens */
public class Protector extends Agent {
	/**A védelem ágens léptetését szimuláló fügvény. */
	public void step() {
	}
	
	/**A függvény paraméterben kapott virológuson fogja kifejteni a hatását az ágens. */
	public void effect(Virologist v) {
	}
	
	/**A függvény paraméterben kapott virológuson szünteti meg a felkent ágens hatását. */
	public void decompose(Virologist v) {
	}
	
	/**A visitor tervezési mintát ez a függvény valósítja meg, ez fogja fogadni a védelem ágens típust. */
	public void accept(IInventoryVisitor i) {
	}
	
	/**A paraméterben kapott ágenst eltávolítjuk a paraméterben kapott virológusról. */
	public void protect(Virologist v, Agent a) {
	}
	
	/** Az ágens felhasználására irányuló függvény.
	 * @param v1 A felhasználó
	 * @param v2 Az elszenvedő
	 * */
	public void use(Virologist v1, Virologist v2) {
	}

}
