package item;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.RDancer.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import game.Game;
import inventory.IInventoryVisitor;
import inventory.InventorySorterVisitor;

/**
 * A vitustáncot okozó ágens receptje.
 */
public class RDancer extends Recipe {
    /**
     * Ikon elérési út
     */
    protected String iconPath = "resources\\RDancer.png";
    /**
     * A vitustáncot okozó ágenshez szükséges anyagok számai.
     */
    public static int numberOfAminoAcid = 3;
    public static int numberOfNucleoid = 2;

    /**
     * Konstruktor
     */
    public RDancer() {
        super(RDancer.numberOfAminoAcid, RDancer.numberOfNucleoid);
    }

    /**
     * Getter - Ikon elérési út
     */
    public String getIconPath() {
        return iconPath;
    }

    /**
     * A visitor tervezési mintát kihasználva a visitor megnézi, hogy a vitus táncot okozó ágens recepjéhez van-e
     * elegendő alapanyag.
     */
    public boolean hasEnoughMaterial(InventorySorterVisitor i) {
        return (i.getAminoacidItems().size() >= numberOfAminoAcid && i.getNucleoidItems().size() >= numberOfNucleoid);
    }

    /**
     * A visitor tervezési mintát ez a függvény valósítja meg, ez fogja fogadni a vitustánc ágens receptje típust.
     */
    public void accept(IInventoryVisitor i) {
        i.visit(this);
    }


    /**
     * A recept használata után az visszaadja a kész ágenst.
     */
    @Override
    public Agent addAgent() {
        Agent a = new Dancer();
        Game.timer.addSteppable(a);
        return a;
    }
}
