package item;/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.Recipe.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


import inventory.IStorable;

/** */
public abstract class Recipe implements IStorable {
	/** */
	public abstract bool hasEnoughMaterial(inventorySorterVisitor i);
}
