package item;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.Recipe.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import inventory.IStorable;
import inventory.InventorySorterVisitor;

/** A játék során elkészíthető ágensek receptjének az ősosztálya.*/
public abstract class Recipe implements IStorable {
	/**A visitor tervezési mintát kihasználva a visitor megnézi, hogy az  ágens recepjéhez van-e
	 elegendő alapanyag. */
	public abstract boolean hasEnoughMaterial(InventorySorterVisitor i);
}
