package item;/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.RForgetter.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


import inventory.IInventoryVisitor;

/** */
public class RForgetter extends Recipe {
	/** */
	public bool hasEnoughMaterial(inventorySorterVisitor i) {
	}
	
	/** */
	public void accept(IInventoryVisitor i) {
	}
	
	/** */
	public bool hasEnoughMaterial(inventorySorterVisitor i) {
	}
}
