package item;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.RForgetter.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import inventory.IInventoryVisitor;
import inventory.InventorySorterVisitor;

/**
 * A felejtést okozó ágens receptje.
 */
public class RForgetter extends Recipe {
    /**
     * Ikon elérési út
     */
    protected String iconPath = "";
    /**
     * A vitustáncot okozó ágenshez szükséges anyagok számai.
     */
    public static int numberOfAminoAcid = 2;
    public static int numberOfNucleoid = 4;

    /**
     * Konstruktor
     */
    public RForgetter() {
        super(RForgetter.numberOfAminoAcid, RForgetter.numberOfNucleoid);
    }

    /**
     * Getter - Ikon elérési út
     */
    public String getIconPath() {
        return iconPath;
    }

    /**
     * A visitor tervezési mintát kihasználva a visitor megnézi, hogy a felejtést okozó ágens recepjéhez van-e
     * elegendő alapanyag.
     */
    public boolean hasEnoughMaterial(InventorySorterVisitor i) {
        return (i.getAminoacidItems().size() >= numberOfAminoAcid && i.getNucleoidItems().size() >= numberOfNucleoid);
    }

    /**
     * A visitor tervezési mintát ez a függvény valósítja meg, ez fogja fogadni a felejtő ágens receptje típust.
     */
    public void accept(IInventoryVisitor i) {
        i.visit(this);
    }

    /**
     * A recept használata után az visszaadja a kész ágenst.
     */
    @Override
    public Agent addAgent() {
        return new Forgetter();
    }

}
