package item;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.RForgetter.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import inventory.IInventoryVisitor;

/** A felejtést okozó ágens receptje. */
public class RForgetter extends Recipe {
	/** A visitor tervezési mintát kihasználva a visitor megnézi, hogy a felejtést okozó ágens recepjéhez van-e
	 elegendő alapanyag. */
	public boolean hasEnoughMaterial(inventorySorterVisitor i) {
		return true;
	}
	
	/** A visitor tervezési mintát ez a függvény valósítja meg, ez fogja fogadni a felejtő ágens receptje típust. */
	public void accept(IInventoryVisitor i) {
	}
	

}
