package item;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.RProtector.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import inventory.IInventoryVisitor;

/** A védelem  ágens receptje. */
public class RProtector extends Recipe {
	/** A visitor tervezési mintát kihasználva a visitor megnézi, hogy a védelem ágens recepjéhez van-e
	 elegendő alapanyag. */
	public boolean hasEnoughMaterial(inventorySorterVisitor i) {
		return true;
	}
	
	/**A visitor tervezési mintát ez a függvény valósítja meg, ez fogja fogadni a védelem ágens receptje típust. */
	public void accept(IInventoryVisitor i) {
	}
	

}
