package item;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : item.RProtector.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import inventory.IInventoryVisitor;
import inventory.InventorySorterVisitor;

/** A védelem  ágens receptje. */
public class RProtector extends Recipe {
	/** A visitor tervezési mintát kihasználva a visitor megnézi, hogy a védelem ágens recepjéhez van-e
	 elegendő alapanyag. */
	public boolean hasEnoughMaterial(InventorySorterVisitor i) {
		if(i.aminoacidItems.size() >= 2 && i.nucleoidItems.size() >= 3){
			return true;
		}
		else{
			return false;
		}
	}
	
	/**A visitor tervezési mintát ez a függvény valósítja meg, ez fogja fogadni a védelem ágens receptje típust. */
	public void accept(IInventoryVisitor i) {
		i.visit(this);
	}
	

}
