package game;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : game.Game.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/


import entity.Virologist;

/** Játék objektum, felelőssége a játék elindítása, kiléptetése */
public class Game {
	/** Játéktér */
	private Map map;

	/** Új játék indítása, pályagenerálás */
	public void newGame() {
	}
	
	/** Játékból való kilépés */
	public void exitGame() {
	}
	
	/** Egy virológus megnyerte a játékot */
	public void winGame(Virologist v) {
	}
}
