package game;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : game.Laboratory.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import entity.Virologist;
import inventory.NotEnoughSpaceException;
import item.*;
import java.util.Random;

/** Laboratórium mező, rálépéskor egy receptet kínál
 * fel a virológus számára
 * */
public abstract class Laboratory extends Tile {

	/** Itt generálunk egy véletlenszerű receptet. 
	 * @throws NotEnoughSpaceException */
	public abstract void interactedWith(Virologist v) throws NotEnoughSpaceException;

}
