package game;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : game.Laboratory.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import entity.Virologist;
import inventory.NotEnoughSpaceException;
import item.*;
import java.util.Random;

/** Laboratóriumok ősosztálya, egy laboratórium lehet biztonságos ahol a virológus receptet kap és lhet medvevírussal fertőzött.
 * */
public abstract class Laboratory extends Tile {

	/** Itt addjuk hozzá a virológus inventoryjához a mező által generált dolgot.
	 * @throws NotEnoughSpaceException */
	public abstract void interactedWith(Virologist v) throws NotEnoughSpaceException;

}
