package game;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : game.Map.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/



/** */
public class Map {
	/** */
	private Tile tiles;
	
	/** */
	private Steppable steppables;
	
	/** */
	public void addTile(Tile t) {
	}
}
