package game;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : game.Safehouse.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/



/** */
public class Safehouse extends Tile {
	/** */
	public void acceptVirologist(Virologist v) {
	}
	
	/** */
	public void acceptVirologist(Virologist v) {
	}
}
