package game;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : game.Safehouse.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import entity.Virologist;
import inventory.Inventory;
import inventory.ItemNotFoundException;
import inventory.NotEnoughSpaceException;
import item.*;
import java.util.Random;

/** Óvóhely típusú mező, védőfelszerelést
 * kínál a virológusoknak */
public class Safehouse extends Tile {

	/** Itt addjuk hozzá a védőfelszerelést a virológus inventoryjához. */
	public void interactedWith(Virologist v) {
		try {
			Gear g = (Gear) inventory.at(0); 
			v.getInventory().addItem(g);
			inventory.removeItem(g);
		} catch (NotEnoughSpaceException e) {
			e.printStackTrace();
		} catch (ItemNotFoundException e) {
			e.printStackTrace();
		}
	}

	/**Visszaadja mező inventoryját.*/
	@Override
	public Inventory getInventory() {
		return inventory;
	}
	/**Megtölti a mező inventoryját véletlenszerű védőfelszerelésekkel.*/
	@Override
	public void fillInventory() throws NotEnoughSpaceException {
		Random r = new Random();
		while(inventory.hasSpace()) {
			int n = r.nextInt(3);
			switch (n) {
				case 0:
					inventory.addItem(new Bag());
					break;
				case 1:
					inventory.addItem(new Jacket());
					break;
				case 2:
					inventory.addItem(new Glove());
					break;
				default:
					inventory.addItem(new Axe());
			}
		}
	}
}
