package game;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : game.Safehouse.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import entity.Virologist;
import inventory.Inventory;
import inventory.NotEnoughSpaceException;
import item.*;
import java.util.Random;

/** Óvóhely típusú mező, védőfelszerelést
 * kínál a virológusoknak */
public class Safehouse extends Tile {

	/** Itt generálunk egy véletlenszerű védőfelszerelést. */
	public void interactedWith(Virologist v) {
		System.out.println("Safehouse.interactedWith");
		
	}

	@Override
	public Inventory getInventory() {
		// TODO Auto-generated method stub
		return inventory;
	}

	@Override
	public void fillInventory() throws NotEnoughSpaceException {
		Random r = new Random();
		for(int i=0;i<inventory.size();i++) {
			int n = r.nextInt(3);
			switch (n) {
				case 0:
					inventory.addItem(new Bag());
					break;
				case 1:
					inventory.addItem(new Jacket());
					break;
				case 2:
					inventory.addItem(new Glove());
					break;
				default:
					inventory.addItem(new Axe());
			}
		}
	}
}
