package game;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : game.Steppable.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/



/** Léptethető dolgokat összefoglalő interfész */
public interface Steppable {
	/** A lépést szimuláló függvény */
	public void step();
}
