package game;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : game.Storage.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import entity.Virologist;
import inventory.NotEnoughSpaceException;
import item.*;
import java.util.Random;

/** Raktár mező, a rálépő virológusnak egy
 * véletlenszerű anyagot kínál fel */

public class Storage extends Tile {

	/** Itt generálunk egy véletlenszerű anyagot. */
	public void interactedWith(Virologist v) throws NotEnoughSpaceException {
		System.out.println("Storage.interactedWith");
		Random r = new Random();
		int n = r.nextInt(2);
		System.out.println("v.getInventory");
		if(n == 0) v.getInventory().addItem(new Aminoacid());
		if(n == 1) v.getInventory().addItem(new Nucleoid());
		System.out.println("i.addItem");
	}
}
