package game;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : game.Storage.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import entity.Virologist;
import inventory.Inventory;
import inventory.ItemNotFoundException;
import inventory.NotEnoughSpaceException;
import item.*;
import java.util.Random;

/** Raktár mező, a rálépő virológusnak egy
 * véletlenszerű anyagot kínál fel */

public class Storage extends Tile {

	/** Itt generálunk egy véletlenszerű anyagot. */
	public void interactedWith(Virologist v) throws NotEnoughSpaceException {
		System.out.println("Storage.interactedWith");
		System.out.println("i.addItem");
	}
	
	/**/
	@Override
	public Inventory getInventory() {
		return inventory;
	}
	
	/**/
	@Override
	public void fillInventory() throws NotEnoughSpaceException {
		Random r = new Random();
		for(int i=0;i<inventory.size();i++) {
		int n = r.nextInt(2);
		if(n == 0)inventory.addItem(new Aminoacid());
		if(n == 1)inventory.addItem(new Nucleoid());
		}
	}
}
