package game;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : game.Tile.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import entity.Virologist;
import inventory.NotEnoughSpaceException;

import java.util.ArrayList;

/** Mező ősosztály */
public abstract class Tile {
	/** A mezőn tartózkodó virológusok */
	protected ArrayList<Virologist> virologists;
	/** A mező szomszédai */
	protected ArrayList<Tile> neighbours;

	/** Konstruktor */
	public Tile() {
		virologists = new ArrayList<Virologist>();
		neighbours = new ArrayList<Tile>();
	}

	/** Getter - szomszédok */
	public ArrayList<Tile> getNeighbours() {
		System.out.println("Tile.getNeighbours");
		return neighbours;
	}

	/** Getter - virológusok */
	public ArrayList<Virologist> getVirologist() {
		System.out.println("Tile.getVirologist");
		return virologists;
	}

	/** Virológus hozzáadása a mezőhöz */
	public void addVirologist(Virologist v) {
		System.out.println("Tile.addNeighbours");
		virologists.add(v);
		v.setTile(this);
	}
	
	/** Virológus törlése a mezőről */
	public void removeVirologist(Virologist v) {
		System.out.println("Tile.getNeighbours");
		virologists.remove(v);
	}
	
	/** Szomszéd hozzáadása */
	public void addNeighbour(Tile t) {
		System.out.println("Tile.addNeighbours");
		neighbours.add(t);
	}
	
	/** A virológus így nézi meg, hogy mi található a mezőn */
	public abstract void interactedWith(Virologist v) throws NotEnoughSpaceException;
	/** Virológus befogadása, leszármazott definiálja a viselkedést */
	public abstract void acceptVirologist(Virologist v);
}
