package game;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : game.Timer.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import java.util.ArrayList;

/**
 * Időzítő osztály, a léptethető dolgok léptetéséért felel
 */
public class Timer {
	private static Timer timer = null;
    /**
     * Léptethető objektumok listája
     */
    public static ArrayList<Steppable> steppables;
    /**
     * Konstruktor
     */
    private Timer() {
        steppables  = new ArrayList<Steppable>();
    }
    
    public static Timer getInstance() {
    	if(timer == null) timer = new Timer();
    	return timer;
    }

    /**
     * A léptethető objektumokon egyszer
     * meghívjuk a lépést
     */
    public void tick() {
        for (Steppable s : steppables) {
            try {
                s.step();
            } catch (Exception ignored) {
            }
        }
    }

    /**
     * Léptethető objektum hozzáadása
     */
    public void addSteppable(Steppable s) {
        steppables.add(s);
    }

    /**
     * Léptethető objektum törlése
     */
    public void removeSteppable(Steppable s) {
        steppables.remove(s);
    }
}
