package game;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : game.Timer.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import java.util.ArrayList;

/** Időzítő osztály, a léptethető dolgok léptetéséért felel */
public class Timer {
	/** Léptethető objektumok listája */
	private ArrayList<Steppable> steppables;

	/** Konstruktor */
	public Timer(){
		steppables = new ArrayList<Steppable>();
	}
	
	/** A léptethető objektumokon egyszer
	 * meghívjuk a lépést */
	public void tick() {
		System.out.println("Timer.tick");
		for(Steppable s : steppables){
			s.step();
		}
	}
	
	/** Léptethető objektum hozzáadása */
	public void addSteppable(Steppable s) {
		System.out.println("Timer.addSteppable");
		steppables.add(s);
	}
	
	/** Léptethető objektum törlése */
	public void removeSteppable(Steppable s) {
		System.out.println("Timer.removeSteppable");
		steppables.remove(s);
	}
}
