package game;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : game.Town.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/



/** */
public class Town extends Tile {
	/** */
	public void acceptVirologist(Virologist v) {
	}
	
	/** */
	public void acceptVirologist(Virologist v) {
	}
}
