package game;

/*

  Generated by StarUML(tm) Java Add-In

  @ Project : Varazsbogyok
  @ File Name : game.Town.java
  @ Date : 2022. 03. 23.
  @ Author : varazsbogyok

*/

import entity.Virologist;
import inventory.Inventory;
import inventory.NotEnoughSpaceException;

/** Város mező, általános célú terep, nincs
 * konkrét funkciója */
public class Town extends Tile {

	/** A virológus így nézi meg, hogy mi található a mezőn */
	public void interactedWith(Virologist v) {
		System.out.println("Town.interactedWith");
	}

	@Override
	public Inventory getInventory() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void fillInventory() throws NotEnoughSpaceException {
		// TODO Auto-generated method stub
		
	}
}
